language: generic
sudo: required
services:
    - docker

before_install:
  - docker build -t jpmora/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jpmora/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-753645421930"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: 
    secure: "$AWS_SECRET_KEY"